TREE = [
    'TTTTTTTTTTKKKKKKTTTTTTTTTT',
    'TTTTTTTKKKMMMMMMKKKTTTTTTT',
    'TTTTTKKMMMMMMMMMMMMKKTTTTT',
    'TTTTKMMMMMMNNNNMMMMMMKTTTT',
    'TTTKMMMMMNNNNNNNNMMMMMKTTT',
    'TTKMMMMMNNNNNNNNNNMMMMMKTT',
    'TKMMMMMNNNNNNNNNNNNMMMMKTT',
    'TKMMMMNNNNNNNNNNNNNNMMMMKT',
    'KMMMMNNNNNNNNNNNNNNNNMMMMK',
    'KMMMNNNNNNNEEEENNNNNNNMMMK',
    'KMMMNNNNNNEEEEEEENNNNNMMMK',
    'KMMNNNNNNNEEEEEEEENNNNNMMK',
    'TKNNNNNNNNEEEEEEEENNNNNNKT',
    'TKNNNNNNNNEEEEEEEENNNNNNKT',
    'TTKNNNNNNNEEEEEEEENNNNNKTT',
    'TTTKKNNNNNEEEEEEENNNNKKTTT',
    'TTTTTKKNNNEEEEEENNNKKTTTTT',
    'TTTTTTTKKNEEEEEENKKTTTTTTT',
    'TTTTTTTTTKKEEEEKKTTTTTTTTT',
    'TTTTTTTTTTTKBBKTTTTTTTTTTT',
    'TTTTTTTTTTTKBDBKTTTTTTTTTT',
    'TTTTTTTTTTTKBDBKTTTTTTTTTT',
    'TTTTTTTTTTTKKKKKTTTTTTTTTT',
    'TTTTTTTTTTTKKKKKTTTTTTTTTT',
    'TTTTTTTTTTKKKKKKKTTTTTTTTT',
    'TTTTTTTTTKKKKKKKKKTTTTTTTT',
    'TTTTTTTTTKKKKKKKKKTTTTTTTT'
]

BONFIRE_1 = [
    'TTTTTFTTTTT',
    'TTTTFOFTTTT',
    'TTTOOOFTTTT',
    'TTFOOSOFTTT',
    'TFOOSSOOFTT',
    'TFOOSSSOFTT',
    'FOOSSSSSOFT',
    'KDKKBBKKDKT',
    'TKDBKKBDKTT',
    'TTKKKKKTTTT'
]

BONFIRE_2 = [
    'TTTTTTFTTTT',
    'TTTTTFOFTTT',
    'TTTTOOFTTTT',
    'TTTOOSOFTTT',
    'TTFOOSOOFTT',
    'TFOOSSSOFTT',
    'FOOSSSSSOFT',
    'KDKKBBKKDKT',
    'TKDBKKBDKTT',
    'TTKKKKKTTTT'
]

BUSH = [
    'TTTTTTMMMMMNTTTTTT',
    'TTTTMMMMMMNNNNTTTT',
    'TTTMMMMMMNNNNNETTT',
    'TTMMMMMMMNNNNNEETT',
    'TMMMMMMNNNNNEEEEET',
    'MMMMMNNNNNEEEEEEEE',
    'MMMMNNNNNNEEEEEEEE'
]

FLOWER = [
    'TRT',
    'RPR',
    'TRT',
    'TNT',
    'MNN'
]

ROCK = [
    'TTGGTT',
    'TGGGGT',
    'GDDGGA',
    'DAAADA'
]

SUN = [
    'TTTTTTTSTTTTTTT',
    'TTTTTTTSTTTTTTT',
    'TTSTTTTSTTTTSTT',
    'TTTSTOOSSOOSTTT',
    'TTTTOOSSSSOOTTT',
    'TTTOSSSYYSSSOTT',
    'TTOSSYYYYYYSSOT',
    'SSOSYYYYYYYYOSS',
    'TTOSSYYYYYYSSOT',
    'TTTOSSSYYSSSOTT',
    'TTTTOOSSSSOOTTT',
    'TTTSTOOSSOOSTTT',
    'TTSTTTTSTTTTSTT',
    'TTTTTTTSTTTTTTT',
    'TTTTTTTSTTTTTTT'
]

MOON = [
    'TTTTTCCCCCCCTTTT',
    'TTTCCVVVVCCCCCCT',
    'TTCVVVVVVVVCCCCT',
    'TCCVVVVVCCCVVVCT',
    'TCCCVVVCCCCVVVCT',
    'TCCCCCCCCCCVVVCT',
    'CCCVCCCCCCCCCCCC',
    'CCVVVCCCCCCCCCCC',
    'CCVVVCCCCCVVVCCC',
    'CCCVCCCCCVVVVVCC',
    'TCCCCCCCCCVVVVCT',
    'TCCCCCCCCCCVVVCT',
    'TTCCCCCVVVCCCCTT',
    'TTTCCCCCVCCCCCTT',
    'TTTTTCCCCCCCTTTT',
    'TTTTTTTTTTTTTTTT'
]

CLOUD = [
    'TTTTTTTTYYYYTTTTTTTT',
    'TTTTTTYYYYYYYYTTTTTT',
    'TTTTYYYYYYYYYYYYTTTT',
    'TTYYYYYYYYYYYYYYYYTT',
    'YYYYYYYYYYYYYYYYYYYY',
    'YYYYYYYYYYYYYYYYYYYY',
    'TYYYYYYYYYYYYYYYYYYT'
]
